# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x10\x63om.example.grpc\"\x0e\n\x0cHelloRequest\"]\n\x06\x41uthor\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x15\n\rdate_of_birth\x18\x03 \x01(\t\x12\x15\n\rdate_of_death\x18\x04 \x01(\t\"m\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12(\n\x06\x61uthor\x18\x02 \x01(\x0b\x32\x18.com.example.grpc.Author\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\x12\r\n\x05genre\x18\x05 \x03(\t\"<\n\x13\x42ooksAuthorsRequest\x12%\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x16.com.example.grpc.Book2n\n\x0eLibraryService\x12\\\n\x13SendBooksAndAuthors\x12%.com.example.grpc.BooksAuthorsRequest\x1a\x1e.com.example.grpc.HelloRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=35
  _globals['_HELLOREQUEST']._serialized_end=49
  _globals['_AUTHOR']._serialized_start=51
  _globals['_AUTHOR']._serialized_end=144
  _globals['_BOOK']._serialized_start=146
  _globals['_BOOK']._serialized_end=255
  _globals['_BOOKSAUTHORSREQUEST']._serialized_start=257
  _globals['_BOOKSAUTHORSREQUEST']._serialized_end=317
  _globals['_LIBRARYSERVICE']._serialized_start=319
  _globals['_LIBRARYSERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
